# Generated by Django 4.0.5 on 2022-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='enviado_por',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
