# Generated by Django 4.0.5 on 2022-06-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receitas', '0002_receita_enviado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
        ),
    ]
